package pipe.gui.widgets;

import pipe.controllers.PetriNetController;
import pipe.controllers.PlaceController;
import pipe.gui.ApplicationSettings;
import pipe.models.petrinet.PetriNet;
import pipe.models.component.token.Token;
import pipe.views.ArcView;
import pipe.views.PetriNetView;
import pipe.views.TransitionView;

import javax.swing.*;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.util.*;
import java.util.List;

/**
 * @author pere
 */
public class PlaceEditorPanel extends javax.swing.JPanel {
    private final PetriNetController netController;
    private final PlaceController placeController;
    private final PetriNetView petriNetView;
    private final JRootPane rootPane;

    private javax.swing.JLabel capacity0Label = new javax.swing.JLabel();
    private javax.swing.JSpinner capacitySpinner = new javax.swing.JSpinner();
    private javax.swing.JTextField nameTextField = new javax.swing.JTextField();
    private javax.swing.JButton okButton = new javax.swing.JButton();
    private List<JSpinner> inputtedMarkings = new LinkedList<JSpinner>();
    private List<String> inputtedTokenClassNames = new LinkedList<String>();

    /**
     * Creates new form PlaceEditor
     *
     * @param rootPane
     * @param petriNetView
     */
    public PlaceEditorPanel(JRootPane rootPane, PlaceController placeController,
                            PetriNetView petriNetView) {

        this.rootPane = rootPane;
        this.rootPane.setDefaultButton(okButton);
        this.placeController = placeController;
        this.petriNetView = petriNetView;

        //TOOD: PASS IN AS ARG
        netController = ApplicationSettings.getApplicationController()
                .getActivePetriNetController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new java.awt.GridBagLayout());
        JPanel placeEditorPanel = createPlaceEditorPanel();

        // Now set new dimension used in for loop below
        int col = 0;
        int row = 2;

        PetriNet net = ApplicationSettings.getApplicationController()
                .getActivePetriNetController().getPetriNet();
        for (Token token : net.getTokens()) {
            if (token.isEnabled()) {
                JLabel tokenClassName = new JLabel();
                JSpinner tokenClassMarking = new JSpinner();
                inputtedMarkings.add(tokenClassMarking);

                tokenClassName.setText(token.getId() + ": ");
                inputtedTokenClassNames.add(token.getId());
                final GridBagConstraints tokenNameConstraints =
                        new java.awt.GridBagConstraints();
                tokenNameConstraints.gridx = 0;
                tokenNameConstraints.gridy = row;
                tokenNameConstraints.anchor = java.awt.GridBagConstraints.EAST;
                tokenNameConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
                placeEditorPanel.add(tokenClassName, tokenNameConstraints);

                tokenClassMarking
                        .setValue(placeController.getTokenCount(token));
                tokenClassMarking
                        .setMinimumSize(new java.awt.Dimension(50, 20));
                tokenClassMarking
                        .setPreferredSize(new java.awt.Dimension(50, 20));
                tokenClassMarking.addChangeListener(
                        new javax.swing.event.ChangeListener() {
                            public void stateChanged(
                                    javax.swing.event.ChangeEvent evt) {
                                markingSpinnerStateChanged(evt,
                                        inputtedMarkings.size() - 1);
                            }
                        });

                final GridBagConstraints tokenValueConstraints =
                        new java.awt.GridBagConstraints();
                tokenValueConstraints.gridx = col + 1;
                tokenValueConstraints.gridy = row;
                tokenValueConstraints.gridwidth = 3;
                tokenValueConstraints.fill =
                        java.awt.GridBagConstraints.HORIZONTAL;
                tokenValueConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
                placeEditorPanel.add(tokenClassMarking, tokenValueConstraints);
                row++;
            }
        }

        initializeCapacityLabel(placeEditorPanel, row);
        initializeCapacitySpinner(placeEditorPanel, row);
        initializeCapacity0Label(placeEditorPanel, row);
        row++;

        GridBagConstraints gridBagConstraints;

        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new java.awt.GridBagLayout());
        initializeOkButton(buttonPanel);
        initializeCancelButton(buttonPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(buttonPanel, gridBagConstraints);

    }

    /**
     * Sets the no capacity restriction label visible if the capacity is
     * zero
     *
     * @param capacity
     */
    private void setCapacityVisible(double capacity) {
        if (capacity == 0) {
            capacity0Label.setVisible(true);
        }
        else {
            capacity0Label.setVisible(false);
        }

    }

    private void initializeCapacity0Label(JPanel placeEditorPanel, int row) {
        capacity0Label.setText("(no capacity restriction)    ");
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = row;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        placeEditorPanel.add(capacity0Label, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 8, 5, 8);
        add(placeEditorPanel, gridBagConstraints);
        setCapacityVisible(placeController.getCapacity());
    }

    private void initializeCapacitySpinner(JPanel placeEditorPanel, int row) {
        capacitySpinner.setModel(
                new SpinnerNumberModel(placeController.getCapacity(), 0,
                        Integer.MAX_VALUE, 1));
        capacitySpinner.setMinimumSize(new Dimension(50, 20));
        capacitySpinner.setPreferredSize(new Dimension(50, 20));
        capacitySpinner.addChangeListener(new ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                capacitySpinnerStateChanged(evt);
            }
        });

        final GridBagConstraints capacityConstraints = new GridBagConstraints();
        capacityConstraints.gridx = 1;
        capacityConstraints.gridy = row;
        capacityConstraints.fill = GridBagConstraints.HORIZONTAL;
        capacityConstraints.insets = new Insets(3, 3, 3, 3);
        placeEditorPanel.add(capacitySpinner, capacityConstraints);
    }

    private JPanel createPlaceEditorPanel() {
        GridBagConstraints gridBagConstraints;
        JPanel placeEditorPanel = new JPanel();
        placeEditorPanel.setLayout(new GridBagLayout());

        placeEditorPanel
                .setBorder(BorderFactory.createTitledBorder("Place Editor"));

        JLabel nameLabel = new JLabel();
        nameLabel.setText("NameDetails:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        placeEditorPanel.add(nameLabel, gridBagConstraints);

        initializeNameTextField(placeEditorPanel);
        return placeEditorPanel;
    }

    private void initializeCapacityLabel(JPanel placeEditorPanel, int row) {
        GridBagConstraints gridBagConstraints;
        JLabel capacityLabel = new JLabel();
        capacityLabel.setText("Capacity:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = row;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        placeEditorPanel.add(capacityLabel, gridBagConstraints);
    }

    private void initializeCancelButton(JPanel buttonPanel) {
        GridBagConstraints gridBagConstraints;
        JButton cancelButton = new JButton();
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonHandler(evt);
            }
        });

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(8, 0, 8, 10);
        buttonPanel.add(cancelButton, gridBagConstraints);
    }

    private void initializeNameTextField(JPanel placeEditorPanel) {
        nameTextField.setText(placeController.getName());
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        placeEditorPanel.add(nameTextField, gridBagConstraints);
    }

    private void initializeOkButton(JPanel buttonPanel) {
        okButton.setText("OK");
        okButton.setMaximumSize(new Dimension(75, 25));
        okButton.setMinimumSize(new Dimension(75, 25));
        okButton.setPreferredSize(new Dimension(75, 25));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonHandler(evt);
            }
        });
        okButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okButtonKeyPressed(evt);
            }
        });

        GridBagConstraints gridBagConstraints =
                new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 9);
        buttonPanel.add(okButton, gridBagConstraints);
    }

    private void markingSpinnerStateChanged(javax.swing.event.ChangeEvent evt,
                                            int posInList) {//GEN-FIRST:event_markingSpinnerStateChanged
/*      Integer capacity = (Integer)capacitySpinner.getValue();
      int totalMarkings = 0;
      for(JSpinner inputtedMarking:inputtedMarkings){
    	  totalMarkings += (Integer)inputtedMarking.getValue();
      }
      int markingOfCurrentSpinner = (Integer)inputtedMarkings.get(posInList).getValue();
      if (capacity > 0) {
         if (totalMarkings > capacity) {
        	 int overMarkingLimit = totalMarkings - capacity;
        	 inputtedMarkings.get(posInList).setValue(markingOfCurrentSpinner - overMarkingLimit);
         }
      }*/
    }//GEN-LAST:event_markingSpinnerStateChanged

    private final ChangeListener changeListener =
            new javax.swing.event.ChangeListener() {
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    JSpinner spinner = (JSpinner) evt.getSource();
                    JSpinner.NumberEditor numberEditor =
                            ((JSpinner.NumberEditor) spinner.getEditor());
                    numberEditor.getTextField()
                            .setBackground(new Color(255, 255, 255));
                    spinner.removeChangeListener(this);
                }
            };

    private void okButtonKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            doOK();
        }
    }

    private void doOK() {

        if (!setCapacity()) {
            return;
        }

        boolean successfullySet = setTokenValues();
        if (!successfullySet) {
            return;
        }

        boolean successfulName = setNameValue();
        if (!successfulName) {
            return;
        }

        updateArcAndTran();
        exit();
    }

    private boolean setCapacity() {
        Integer newCapacity;

        try {
            newCapacity = (Integer) capacitySpinner.getValue();
        } catch (Exception e) {
            JSpinner.NumberEditor numberEditor =
                    ((JSpinner.NumberEditor) capacitySpinner.getEditor());
            numberEditor.getTextField().setBackground(new Color(255, 0, 0));
            capacitySpinner.addChangeListener(changeListener);
            capacitySpinner.requestFocusInWindow();
            return false;
        }

        placeController.setCapacity(newCapacity);
        return true;
    }

    private Double getCapacitySpinnerValue() {
        return (Double) capacitySpinner.getValue();
    }

    /**
     * @return return false if could not set name
     */
    private boolean setNameValue() {
        String newName = nameTextField.getText();
        if (!newName.equals(placeController.getName())) {
            if (petriNetView.checkPlaceIDAvailability(newName)) {
                placeController.setName(newName);
            }
            else {
                // aquest nom no est disponible...
                JOptionPane.showMessageDialog(null,
                        "There is already a place named " + newName, "Error",
                        JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        return true;
    }

    /**
     * Sets the token values on the place
     *
     * @return true if it was able to set token values, false if not.
     */
    private boolean setTokenValues() {
        int totalCount = calculateTokenCount();
        if (placeController.hasCapacityRestriction() &&
                totalCount > getCapacitySpinnerValue()) {
            JOptionPane.showMessageDialog(null,
                    "Token counts exceed the capacity of place. Please alter capacity or tokens");
            return false;
        }

        Map<Token, Integer> newTokenCounts = new HashMap<Token, Integer>();
        for (int tokenIndex = 0; tokenIndex < inputtedMarkings.size();
             tokenIndex++) {
            String tokenName = inputtedTokenClassNames.get(tokenIndex);
            int newTokenCount = Integer.valueOf(
                    (Integer) inputtedMarkings.get(tokenIndex).getValue());

            try {
                if (newTokenCount < 0) {
                    JOptionPane.showMessageDialog(null,
                            "Marking cannot be less than 0. Please re-enter");
                    return false;
                }

                Token token = netController.getToken(tokenName);
                if (placeController.getTokenCount(token) != newTokenCount) {
                    newTokenCounts.put(token, newTokenCount);
                }

            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null,
                        "Please enter a positive integer greater or equal to 0.",
                        "Invalid entry", JOptionPane.ERROR_MESSAGE);
                return false;
            } catch (Exception exc) {
                exc.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "Please enter a positive integer greater or equal to 0.",
                        "Invalid entry", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        placeController.setTokenCounts(newTokenCounts);
        return true;
    }

    /**
     * @return the total number of tokens declared for the place
     */
    private int calculateTokenCount() {
        int sum = 0;
        for (int tokenIndex = 0; tokenIndex < inputtedMarkings.size();
             tokenIndex++) {
            Object value = inputtedMarkings.get(tokenIndex).getValue();
            sum += Integer.valueOf((Integer) value);
        }
        return sum;
    }

    private void updateArcAndTran() {
        Collection<ArcView> arcs = ApplicationSettings.getApplicationView()
                .getCurrentPetriNetView().getArcsArrayList();
        for (ArcView arc : arcs) {
            arc.repaint();
        }
        Collection<TransitionView> trans =
                ApplicationSettings.getApplicationView()
                        .getCurrentPetriNetView().getTransitionsArrayList();
        for (TransitionView transition : trans) {
            transition.update();
        }
    }

    private void okButtonHandler(java.awt.event.ActionEvent evt) {
        doOK();
    }

    private void exit() {
        rootPane.getParent().setVisible(false);
    }

    private void cancelButtonHandler(java.awt.event.ActionEvent evt) {
        exit();
    }

    private void capacitySpinnerStateChanged(
            javax.swing.event.ChangeEvent evt) {
        Double capacity = (Double) capacitySpinner.getValue();
        setCapacityVisible(capacity);
    }

}
